---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен запрашивать согласие на принятие cookie
  - При оформление заказа пользователь должен вписать свои данные для связи с ним
  - Пользователь должен иметь возможность ставить оценку товару
  - Пользователь должен иметь возможность выбирать количество товаров при добавлении их в корзину
  - Пользователь должен получать уведомление, что товар был успешно добавлен в корзину
  - При клике на логотип магазина открывается главная страница
  - Должна быть пагинация на странице просмотра товаров
  - На странице корзины должна быть таблица с заголовками "Наименование", "Количество", "Цена". Внутри неё находятся добавленные товары.
  - На странице корзины должна быть возможность удалить товар
  - На странице корзины должна быть возможность увеличить или уменьшить количество товара для заказа
  - Должна быть возможность выбирать количество товара при его добавлении
# new
  - На странице каталога и на странице товара должен выводиться рейтинг товара, его название и цена со скидкой и без
  - Пользователь должен иметь возможность продолжить покупки в каталоге после добавления товара в корзину
  - Вывод товаров в каталоге должен быть постраничным
  - Должна быть возможность оформить заказ с переходом на страницу оплаты
  - Пользователь должен получить информацию о заказе после успешной оплаты