---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен запрашивать согласие на принятие cookie.
  - При оформление заказа пользователь должен вписать свои данные для связи с ним.
  - Пользователь должен иметь возможность ставить оценку товару.
  - Пользователь должен иметь возможность выбирать количество товаров при добавлении их в корзину.
  - Пользователь должен получать уведомление, что товар был успешно добавлен в корзину.
  - При клике на логотип магазина открывается главная страница.
